package cn.flashpool.domain;
// Generated 2018-11-17 14:12:14 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin", catalog = "shareinspiration")
public class Admin implements java.io.Serializable {

	private Integer AId;
	private String AName;
	private String APw;
	private String ANickname;
	private Character AType;

	public Admin() {
	}

	public Admin(String AName, String APw, String ANickname, Character AType) {
		this.AName = AName;
		this.APw = APw;
		this.ANickname = ANickname;
		this.AType = AType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "A_id", unique = true, nullable = false)
	public Integer getAId() {
		return this.AId;
	}

	public void setAId(Integer AId) {
		this.AId = AId;
	}

	@Column(name = "A_name", length = 15)
	public String getAName() {
		return this.AName;
	}

	public void setAName(String AName) {
		this.AName = AName;
	}

	@Column(name = "A_pw", length = 20)
	public String getAPw() {
		return this.APw;
	}

	public void setAPw(String APw) {
		this.APw = APw;
	}

	@Column(name = "A_nickname", length = 24)
	public String getANickname() {
		return this.ANickname;
	}

	public void setANickname(String ANickname) {
		this.ANickname = ANickname;
	}

	@Column(name = "A_type", length = 1)
	public Character getAType() {
		return this.AType;
	}

	public void setAType(Character AType) {
		this.AType = AType;
	}

}
