package cn.flashpool.domain;
// Generated 2018-11-17 14:12:14 by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Note generated by hbm2java
 */
@Entity
@Table(name = "note", catalog = "shareinspiration")
public class Note implements java.io.Serializable {

	private NoteId id;
	private Poolfriend poolfriend;
	private Topic topic;
	private String NTitle;
	private String NTextLoc;
	private String NImgLoc;
	private String NAttachLoc;

	public Note() {
	}

	public Note(NoteId id, Poolfriend poolfriend, Topic topic) {
		this.id = id;
		this.poolfriend = poolfriend;
		this.topic = topic;
	}

	public Note(NoteId id, Poolfriend poolfriend, Topic topic, String NTitle, String NTextLoc, String NImgLoc,
			String NAttachLoc) {
		this.id = id;
		this.poolfriend = poolfriend;
		this.topic = topic;
		this.NTitle = NTitle;
		this.NTextLoc = NTextLoc;
		this.NImgLoc = NImgLoc;
		this.NAttachLoc = NAttachLoc;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "NId", column = @Column(name = "N_id", nullable = false)),
			@AttributeOverride(name = "pyId", column = @Column(name = "PY_id", nullable = false)),
			@AttributeOverride(name = "TId", column = @Column(name = "T_id", nullable = false)) })
	public NoteId getId() {
		return this.id;
	}

	public void setId(NoteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PY_id", nullable = false, insertable = false, updatable = false)
	public Poolfriend getPoolfriend() {
		return this.poolfriend;
	}

	public void setPoolfriend(Poolfriend poolfriend) {
		this.poolfriend = poolfriend;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "T_id", nullable = false, insertable = false, updatable = false)
	public Topic getTopic() {
		return this.topic;
	}

	public void setTopic(Topic topic) {
		this.topic = topic;
	}

	@Column(name = "N_title", length = 90)
	public String getNTitle() {
		return this.NTitle;
	}

	public void setNTitle(String NTitle) {
		this.NTitle = NTitle;
	}

	@Column(name = "N_text_loc", length = 100)
	public String getNTextLoc() {
		return this.NTextLoc;
	}

	public void setNTextLoc(String NTextLoc) {
		this.NTextLoc = NTextLoc;
	}

	@Column(name = "N_img_loc", length = 100)
	public String getNImgLoc() {
		return this.NImgLoc;
	}

	public void setNImgLoc(String NImgLoc) {
		this.NImgLoc = NImgLoc;
	}

	@Column(name = "N_attach_loc", length = 100)
	public String getNAttachLoc() {
		return this.NAttachLoc;
	}

	public void setNAttachLoc(String NAttachLoc) {
		this.NAttachLoc = NAttachLoc;
	}

}
