package cn.flashpool.domain;
// Generated 2018-11-17 14:12:14 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NoteId generated by hbm2java
 */
@Embeddable
public class NoteId implements java.io.Serializable {

	private int NId;
	private int pyId;
	private int TId;

	public NoteId() {
	}

	public NoteId(int NId, int pyId, int TId) {
		this.NId = NId;
		this.pyId = pyId;
		this.TId = TId;
	}

	@Column(name = "N_id", nullable = false)
	public int getNId() {
		return this.NId;
	}

	public void setNId(int NId) {
		this.NId = NId;
	}

	@Column(name = "PY_id", nullable = false)
	public int getPyId() {
		return this.pyId;
	}

	public void setPyId(int pyId) {
		this.pyId = pyId;
	}

	@Column(name = "T_id", nullable = false)
	public int getTId() {
		return this.TId;
	}

	public void setTId(int TId) {
		this.TId = TId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NoteId))
			return false;
		NoteId castOther = (NoteId) other;

		return (this.getNId() == castOther.getNId()) && (this.getPyId() == castOther.getPyId())
				&& (this.getTId() == castOther.getTId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNId();
		result = 37 * result + this.getPyId();
		result = 37 * result + this.getTId();
		return result;
	}

}
