package cn.flashpool.domain;
// Generated 2018-11-17 14:12:14 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Poolfriend generated by hbm2java
 */
@Entity
@Table(name = "poolfriend", catalog = "shareinspiration")
public class Poolfriend implements java.io.Serializable {

	private int pyId;
	private String pyName;
	private Character pyMobile;
	private Character pyCountryCode;
	private String pyStatus;
	private Character pySex;
	private String pyRealName;
	private String pyEmail;
	private String pyNickname;
	private String pyAvatar;
	private String pyIntro;
	private String pyCity;
	private Date pyBirth;
	private String pyCareer;
	private Integer pyTopicNum;
	private Integer pyNoteNum;
	private Set<Note> notes = new HashSet<Note>(0);

	public Poolfriend() {
	}

	public Poolfriend(int pyId) {
		this.pyId = pyId;
	}

	public Poolfriend(int pyId, String pyName, Character pyMobile, Character pyCountryCode, String pyStatus,
			Character pySex, String pyRealName, String pyEmail, String pyNickname, String pyAvatar, String pyIntro,
			String pyCity, Date pyBirth, String pyCareer, Integer pyTopicNum, Integer pyNoteNum, Set<Note> notes) {
		this.pyId = pyId;
		this.pyName = pyName;
		this.pyMobile = pyMobile;
		this.pyCountryCode = pyCountryCode;
		this.pyStatus = pyStatus;
		this.pySex = pySex;
		this.pyRealName = pyRealName;
		this.pyEmail = pyEmail;
		this.pyNickname = pyNickname;
		this.pyAvatar = pyAvatar;
		this.pyIntro = pyIntro;
		this.pyCity = pyCity;
		this.pyBirth = pyBirth;
		this.pyCareer = pyCareer;
		this.pyTopicNum = pyTopicNum;
		this.pyNoteNum = pyNoteNum;
		this.notes = notes;
	}

	@Id

	@Column(name = "PY_id", unique = true, nullable = false)
	public int getPyId() {
		return this.pyId;
	}

	public void setPyId(int pyId) {
		this.pyId = pyId;
	}

	@Column(name = "PY_name", length = 15)
	public String getPyName() {
		return this.pyName;
	}

	public void setPyName(String pyName) {
		this.pyName = pyName;
	}

	@Column(name = "PY_mobile", length = 1)
	public Character getPyMobile() {
		return this.pyMobile;
	}

	public void setPyMobile(Character pyMobile) {
		this.pyMobile = pyMobile;
	}

	@Column(name = "PY_country_code", length = 1)
	public Character getPyCountryCode() {
		return this.pyCountryCode;
	}

	public void setPyCountryCode(Character pyCountryCode) {
		this.pyCountryCode = pyCountryCode;
	}

	@Column(name = "PY_status", length = 20)
	public String getPyStatus() {
		return this.pyStatus;
	}

	public void setPyStatus(String pyStatus) {
		this.pyStatus = pyStatus;
	}

	@Column(name = "PY_sex", length = 1)
	public Character getPySex() {
		return this.pySex;
	}

	public void setPySex(Character pySex) {
		this.pySex = pySex;
	}

	@Column(name = "PY_real_name", length = 39)
	public String getPyRealName() {
		return this.pyRealName;
	}

	public void setPyRealName(String pyRealName) {
		this.pyRealName = pyRealName;
	}

	@Column(name = "PY_email", length = 320)
	public String getPyEmail() {
		return this.pyEmail;
	}

	public void setPyEmail(String pyEmail) {
		this.pyEmail = pyEmail;
	}

	@Column(name = "PY_nickname", length = 24)
	public String getPyNickname() {
		return this.pyNickname;
	}

	public void setPyNickname(String pyNickname) {
		this.pyNickname = pyNickname;
	}

	@Column(name = "PY_avatar", length = 100)
	public String getPyAvatar() {
		return this.pyAvatar;
	}

	public void setPyAvatar(String pyAvatar) {
		this.pyAvatar = pyAvatar;
	}

	@Column(name = "PY_intro", length = 100)
	public String getPyIntro() {
		return this.pyIntro;
	}

	public void setPyIntro(String pyIntro) {
		this.pyIntro = pyIntro;
	}

	@Column(name = "PY_city", length = 15)
	public String getPyCity() {
		return this.pyCity;
	}

	public void setPyCity(String pyCity) {
		this.pyCity = pyCity;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PY_birth", length = 10)
	public Date getPyBirth() {
		return this.pyBirth;
	}

	public void setPyBirth(Date pyBirth) {
		this.pyBirth = pyBirth;
	}

	@Column(name = "PY_career", length = 30)
	public String getPyCareer() {
		return this.pyCareer;
	}

	public void setPyCareer(String pyCareer) {
		this.pyCareer = pyCareer;
	}

	@Column(name = "PY_topic_num")
	public Integer getPyTopicNum() {
		return this.pyTopicNum;
	}

	public void setPyTopicNum(Integer pyTopicNum) {
		this.pyTopicNum = pyTopicNum;
	}

	@Column(name = "PY_note_num")
	public Integer getPyNoteNum() {
		return this.pyNoteNum;
	}

	public void setPyNoteNum(Integer pyNoteNum) {
		this.pyNoteNum = pyNoteNum;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poolfriend")
	public Set<Note> getNotes() {
		return this.notes;
	}

	public void setNotes(Set<Note> notes) {
		this.notes = notes;
	}

}
