package cn.flashpool.domain;
// Generated 2018-11-17 14:12:14 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Topic generated by hbm2java
 */
@Entity
@Table(name = "topic", catalog = "shareinspiration")
public class Topic implements java.io.Serializable {

	private Integer TId;
	private String TName;
	private String TIntroLoc;
	private String TIntroImg;
	private Integer TFollowNum;
	private Integer TNoteNum;
	private Set<Note> notes = new HashSet<Note>(0);

	public Topic() {
	}

	public Topic(String TName, String TIntroLoc, String TIntroImg, Integer TFollowNum, Integer TNoteNum,
			Set<Note> notes) {
		this.TName = TName;
		this.TIntroLoc = TIntroLoc;
		this.TIntroImg = TIntroImg;
		this.TFollowNum = TFollowNum;
		this.TNoteNum = TNoteNum;
		this.notes = notes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "T_id", unique = true, nullable = false)
	public Integer getTId() {
		return this.TId;
	}

	public void setTId(Integer TId) {
		this.TId = TId;
	}

	@Column(name = "T_name", length = 30)
	public String getTName() {
		return this.TName;
	}

	public void setTName(String TName) {
		this.TName = TName;
	}

	@Column(name = "T_intro_loc", length = 100)
	public String getTIntroLoc() {
		return this.TIntroLoc;
	}

	public void setTIntroLoc(String TIntroLoc) {
		this.TIntroLoc = TIntroLoc;
	}

	@Column(name = "T_intro_img", length = 100)
	public String getTIntroImg() {
		return this.TIntroImg;
	}

	public void setTIntroImg(String TIntroImg) {
		this.TIntroImg = TIntroImg;
	}

	@Column(name = "T_follow_num")
	public Integer getTFollowNum() {
		return this.TFollowNum;
	}

	public void setTFollowNum(Integer TFollowNum) {
		this.TFollowNum = TFollowNum;
	}

	@Column(name = "T_note_num")
	public Integer getTNoteNum() {
		return this.TNoteNum;
	}

	public void setTNoteNum(Integer TNoteNum) {
		this.TNoteNum = TNoteNum;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "topic")
	public Set<Note> getNotes() {
		return this.notes;
	}

	public void setNotes(Set<Note> notes) {
		this.notes = notes;
	}

}
