package cn.flashpool.domain;
// Generated 2018-11-17 14:12:14 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "shareinspiration")
public class User implements java.io.Serializable {

	private int userId;
	private String userName;
	private String userPassword;
	private String userPhone;
	private int userState;

	public User() {
	}

	public User(int userId, int userState) {
		this.userId = userId;
		this.userState = userState;
	}

	public User(int userId, String userName, String userPassword, String userPhone, int userState) {
		this.userId = userId;
		this.userName = userName;
		this.userPassword = userPassword;
		this.userPhone = userPhone;
		this.userState = userState;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "user_name")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_password")
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "user_phone")
	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	@Column(name = "user_state", nullable = false)
	public int getUserState() {
		return this.userState;
	}

	public void setUserState(int userState) {
		this.userState = userState;
	}

}
